export const URL_API_BACKEND_LOCAL = 'http://localhost:8080'

export const ID_USUARIO_PADRAO_MVP = 1

export const actionTypes = {
    ADICIONAR_ITEM_CARRINHO: 'ADICIONAR_ITEM_CARRINHO',
    REMOVER_ITEM_CARRINHO: 'REMOVER_ITEM_CARRINHO',
    LIMPAR_CARRINHO: 'LIMPAR_CARRINHO',
}